[package]
name = "orb-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.19"
maud = "0.25.0"
sqlite = "0.31.0"
tokio = "1.29.1"
